Avoided `asyncio_default_fixture_loop_scope` pytest warning.
